DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'categories' AND COLUMN_NAME = 'is_archived') THEN
        ALTER TABLE categories ADD COLUMN is_archived BOOLEAN DEFAULT FALSE;
    END IF;
END $$;
